### PR TITLE
[Fixes #210] Because of the introduction of Multi-select custom field a value must be an array

### LINKED ISSUE #210: Multi-select fields are breaking some APIs like `getOrganizationTickets(orgId)`
The introduction of Multi-select fields  in March 2017 in beta and recently in production is breaking some APIs like `getOrganizationTickets(orgId)`

https://support.zendesk.com/hc/en-us/articles/360000032087-New-ticket-field-type-Multi-select

```
org.zendesk.client.v2.ZendeskException: java.lang.IllegalArgumentException: Can not deserialize instance of java.lang.String out of START_ARRAY token
 at [Source: N/A; line: -1, column: -1] (through reference chain: org.zendesk.client.v2.model.Ticket["custom_fields"]->org.zendesk.client.v2.model.CustomFieldValue["value"])

	at org.zendesk.client.v2.Zendesk.complete(Zendesk.java:2139)
	at org.zendesk.client.v2.Zendesk.access$1400(Zendesk.java:91)
	at org.zendesk.client.v2.Zendesk$PagedIterable$PagedIterator.hasNext(Zendesk.java:2341)
	at org.zendesk.client.v2.RealSmokeTest.getOrganizationTickets(RealSmokeTest.java:238)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Can not deserialize instance of java.lang.String out of START_ARRAY token
 at [Source: N/A; line: -1, column: -1] (through reference chain: org.zendesk.client.v2.model.Ticket["custom_fields"]->org.zendesk.client.v2.model.CustomFieldValue["value"])
	at com.ning.http.client.providers.netty.future.NettyResponseFuture.done(NettyResponseFuture.java:220)
	at com.ning.http.client.providers.netty.handler.HttpProtocol.finishUpdate(HttpProtocol.java:194)
	at com.ning.http.client.providers.netty.handler.HttpProtocol.handleChunk(HttpProtocol.java:451)
	at com.ning.http.client.providers.netty.handler.HttpProtocol.handle(HttpProtocol.java:474)
	at com.ning.http.client.providers.netty.handler.Processor.messageReceived(Processor.java:88)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:135)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:452)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.handler.codec.http.HttpClientCodec.handleUpstream(HttpClientCodec.java:92)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:310)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Can not deserialize instance of java.lang.String out of START_ARRAY token
 at [Source: N/A; line: -1, column: -1] (through reference chain: org.zendesk.client.v2.model.Ticket["custom_fields"]->org.zendesk.client.v2.model.CustomFieldValue["value"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:2518)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:2445)
	at org.zendesk.client.v2.Zendesk$PagedAsyncListCompletionHandler.onCompleted(Zendesk.java:1945)
	at org.zendesk.client.v2.Zendesk$PagedAsyncListCompletionHandler.onCompleted(Zendesk.java:1929)
	at com.ning.http.client.AsyncCompletionHandler.onCompleted(AsyncCompletionHandler.java:55)
	at com.ning.http.client.providers.netty.future.NettyResponseFuture.getContent(NettyResponseFuture.java:177)
	at com.ning.http.client.providers.netty.future.NettyResponseFuture.done(NettyResponseFuture.java:214)
	... 41 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_ARRAY token
 at [Source: N/A; line: -1, column: -1] (through reference chain: org.zendesk.client.v2.model.Ticket["custom_fields"]->org.zendesk.client.v2.model.CustomFieldValue["value"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:599)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:41)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:375)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:98)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:308)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:226)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:203)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:23)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:375)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:98)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:308)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:2513)
	... 47 more

```

cc @alecharp 
FYI @stephenc (I imagine we still don't have a real test environment provided by @zendesk ?)

### PR DESCRIPTION
**Pull request by aheritier**
https://support.zendesk.com/hc/en-us/articles/360000032087-New-ticket-field-type-Multi-select

### CODE REVIEW

**Comment by aheritier** [comment]
@johnou Could you review this PR please ?
@alecharp Could you test it ?

**Comment by aheritier** [comment]
I added a multi-select custom field thus master tests are failing : https://opensource.ci.cloudbees.com/job/zendesk-java-client/job/master/14/console
This PR fixes it : https://opensource.ci.cloudbees.com/job/zendesk-java-client/view/change-requests/job/PR-214/

File: src/main/java/org/zendesk/client/v2/Zendesk.java [hunk 1]
```diff
@@ -2368,6 +2368,7 @@ public static ObjectMapper createMapper() {
         mapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
         mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
         mapper.setDateFormat(new ISO8601DateFormat());
+        mapper.enable(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY);
```
Comment (johnou) [inline src/main/java/org/zendesk/client/v2/Zendesk.java]: @aheritier I think a custom Jackson deserializer for CustomFieldValue makes more sense instead of changing the mapper used for all dtos.

Comment (aheritier) [reply src/main/java/org/zendesk/client/v2/Zendesk.java]: Ok Let me check how to do that :-)

Comment (aheritier) [reply src/main/java/org/zendesk/client/v2/Zendesk.java]: Ok it seems I could use `@JsonFormat(with = JsonFormat.Feature.ACCEPT_SINGLE_VALUE_AS_ARRAY)` just for the impacted field but I have to upgrade jackson .. Let me test it


https://stackoverflow.com/questions/39041496/how-to-enforce-accept-single-value-as-array-in-jacksons-deserialization-process

Comment (johnou) [reply src/main/java/org/zendesk/client/v2/Zendesk.java]: If you want to avoid updating Jackson you could do something like this.. https://github.com/cloudbees/zendesk-java-client/blob/42fb254e47733b8e07a66f3fa975b890da3171f2/src/main/java/org/zendesk/client/v2/model/Action.java#L21

Comment (johnou) [reply src/main/java/org/zendesk/client/v2/Zendesk.java]: @aheritier looks like the Action deserializer is doing exactly what you are trying to achieve :+1: might be nice to use the same approach to keep the models consistent.

**Comment by aheritier** [comment]
@johnou Let's see if the CI is happy

File: src/main/java/org/zendesk/client/v2/Zendesk.java (hunk 1 above)
Comment (johnou) [reply src/main/java/org/zendesk/client/v2/Zendesk.java]: if we go ahead with the Jackson update I think we should also apply the same annotation fix to the Action model.

File: pom.xml [hunk 2]
```diff
@@ -99,12 +99,12 @@
     <dependency>
       <groupId>com.fasterxml.jackson.core</groupId>
       <artifactId>jackson-core</artifactId>
-      <version>2.1.4</version>
+      <version>2.9.3</version>
```
Comment (johnou) [inline pom.xml]: at this point we should modify the pom to include the bom, I can handle that if CI passes.

Comment (alecharp) [reply pom.xml]: using the BOM can come after the PR imo.

File: src/main/java/org/zendesk/client/v2/model/CustomFieldValue.java [hunk 3]
```diff
@@ -32,11 +36,18 @@ public void setId(Long id) {
...
 
-    public void setValue(String value) {
+    public void setValue(String[] value) {
         this.value = value;
     }
+
+    @Override
+    public String toString() {
+        return "CustomFieldValue{" + "id=" + id +
+                ", value=" + (value == null ? "null" : Arrays.asList(value).toString()) +
```
Comment (alecharp) [inline src/main/java/org/zendesk/client/v2/model/CustomFieldValue.java]: can be simplier: showing empty array even if the value is `null` is not really a big deal imo. Also, `toString` are usually only used for logger..

File: pom.xml (hunk 2 above)
Comment (johnou) [reply pom.xml]: done

**Comment by johnou** [comment]
@aheritier PTAL.
